version: '3.8'

services:
  scaletent:
    build:
      context: .
      dockerfile: Dockerfile.apple-silicon
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./config:/app/config
      - ./logs:/app/logs
    ports:
      - "8000:8000"  # API
      - "8501:8501"  # Streamlit UI
    environment:
      - PYTHONPATH=/app
      - DEVICE=mps
      # Metal GPU support environment variables
      - PYTORCH_ENABLE_MPS_FALLBACK=1
      # Add environment variables for paths
      - SRC_PATH=/app/src
      - CONFIG_PATH=/app/config
      - DATA_PATH=/app/data
      - LOGS_PATH=/app/logs
    # Remove the generic GPU capabilities and use platform-specific settings
    deploy:
      resources:
        reservations:
          devices:
            - driver: apple-gpu
              count: 1
              capabilities: [gpu]
    platform: linux/arm64  # Specify platform for Apple Silicon
    depends_on:
      - redis
      - mongodb
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    platform: linux/arm64  # Specify platform for Apple Silicon
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  mongodb:
    image: arm64v8/mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    platform: linux/arm64  # Specify platform for Apple Silicon
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  redis_data:
  mongodb_data: 