# ScaleTent - Meet & Greet System Configuration
# Example configuration file

# System settings
system:
  name: "ScaleTent"
  version: "1.0.0"
  log_level: "info"  # debug, info, warning, error, critical
  log_dir: "logs"

# Detection settings
detection:
  model_path: "data/models/yolov8n.pt"  # Path to YOLOv8 model
  confidence_threshold: 0.5             # Detection confidence threshold
  device: "cuda:0"                      # Device to run inference on (cuda:0, cpu)
  classes: [0]                          # Class IDs to detect (0=person in COCO dataset)
  processing_fps: 15                    # Maximum processing FPS to avoid overloading

# Recognition settings
recognition:
  face_detector_model: "data/models/face_detection_model.pb"
  embedder_model: "data/models/facenet_model.pb"
  database_path: "data/profiles"
  face_detection_threshold: 0.6
  similarity_threshold: 0.7
  backend: "facenet"                    # facenet, arcface, or insightface
  device: "cuda:0"                      # Device to run inference on (cuda:0, cpu)

# Camera settings
cameras:
  - id: "main-entrance-01"
    name: "Main Entrance"
    source: "0"                         # Device ID, URL, or file path
    width: 1280
    height: 720
    fps: 30
    processing_fps: 15                  # Frames to process per second
    enabled: true

  - id: "reception-desk-01"
    name: "Reception Desk"
    source: "rtsp://admin:password@192.168.1.101:554/stream1"
    width: 1920
    height: 1080
    fps: 25
    processing_fps: 10
    enabled: true

  # Add more cameras as needed

# API settings
api:
  websocket:
    host: "0.0.0.0"
    port: 8765
    use_ssl: false
    ssl_cert: null
    ssl_key: null
  
  rest:
    host: "0.0.0.0"
    port: 5000
    use_ssl: false
    ssl_cert: null
    ssl_key: null

# Web interface settings
web:
  host: "0.0.0.0"
  port: 5000
  admin_username: "admin"
  admin_password: "changeme"           # Change this in production
  session_secret: "changeme"           # Change this in production
  theme: "light"                       # light or dark

# Privacy settings
privacy:
  data_retention_days: 30              # Days to keep detection data
  face_blur_in_recordings: true        # Blur faces in recorded videos
  consent_required: true               # Require consent for face recognition
  store_recognized_faces: false        # Store faces of recognized individuals
  store_unknown_faces: false           # Store faces of unknown individuals
  log_sensitivity: "medium"            # low, medium, high (controls what's logged)

# Notification settings
notifications:
  enabled: true
  methods:
    webhook:
      enabled: true
      url: "https://example.com/webhook"
      events: ["person_recognized", "new_person_detected", "system_status"]
      
    email:
      enabled: false
      smtp_server: "smtp.example.com"
      smtp_port: 587
      smtp_user: "notifications@example.com"
      smtp_password: "changeme"
      from_address: "notifications@example.com"
      recipients: ["admin@example.com"]
      events: ["person_recognized", "system_error"]
      
    slack:
      enabled: false
      webhook_url: "https://hooks.slack.com/services/XXXXXXXXXXX/YYYYYYYYYYY/ZZZZZZZZZZZZZZZZZZZZZZZZ"
      channel: "#security"
      events: ["person_recognized", "new_person_detected", "system_error"]
      
    sms:
      enabled: false
      service: "twilio"  # twilio, nexmo, etc.
      account_sid: "your_account_sid"
      auth_token: "your_auth_token"
      from_number: "+15551234567"
      to_numbers: ["+15557654321"]
      events: ["system_error"]

# Storage settings
storage:
  save_detection_images: false         # Save images of detections
  detection_image_path: "data/detections"
  save_recognized_images: true         # Save images of recognized individuals
  recognized_image_path: "data/recognized"
  
  database:
    type: "mongodb"                    # mongodb, sqlite, postgresql
    host: "localhost"
    port: 27017
    name: "scaletent"
    username: null
    password: null
    
  s3:
    enabled: false
    bucket: "scaletent-data"
    region: "us-east-1"
    access_key: null
    secret_key: null
    
# Integration settings
integrations:
  crm:
    enabled: false
    type: "salesforce"  # salesforce, hubspot, etc.
    api_key: null
    api_url: null
    
  access_control:
    enabled: false
    type: "custom"  # custom, lenel, etc.
    api_url: "http://localhost:8080/api/access"
    api_key: null
    
  visitor_management:
    enabled: false
    type: "envoy"  # envoy, proxyclick, etc.
    api_url: null
    api_key: null

# Advanced settings
advanced:
  # Detection tracking settings
  tracking:
    enabled: true
    algorithm: "sort"  # sort, deepsort, byte
    max_age: 30        # Maximum number of frames to keep track of disappeared objects
    min_hits: 3        # Minimum number of detection hits to start tracking
    iou_threshold: 0.3 # IOU threshold for matching detections to tracks
    
  # Performance settings
  performance:
    use_tensorrt: true   # Use TensorRT for acceleration if available
    batch_size: 1        # Batch size for detection
    thread_count: 4      # Number of threads for processing
    
  # Debug settings
  debug:
    save_debug_frames: false  # Save debug frames with detection info
    debug_frame_path: "debug/frames"
    profile_performance: false  # Profile and log performance metrics
    visualize_detections: true  # Visualize detections in web interface
"